version: "3.8"
services:
  btg-postgres:
    image: postgres:17.2
    container_name: btg-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - C:\Develop\WebAplicationDotnetRabbitMQ/postgres:/var/lib/postgresql/data
  
  btg-pgadmin:
    image: dpage/pgadmin4:8.13.0
    container_name: btg-pgadmin
    restart: always
    depends_on:
      - btg-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8090:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
  
  btg-rabbitmq:
    image: rabbitmq:3-management
    hostname: btg-rabbitmq
    ports:
     - "15672:15672"
     - "5672:5672"
    labels:
      NAME: "btg-rabbitmq"

